before_start="""

§6      ___________   ____   ______   __________   §c____     __   ___________   ___________
§6     /____  ____/| / _  | / __  /| /  _______/| §c/ _  |   / /| / _______  /| / _________/|
§6     |___/ /____|// / | |//| / / // /|_______|/§c/ / | |  / / // /|_____/ / // /_________|/
§6        / //     / / /|_ // / / // //         §c/ / /| | / / // //_____/ / /\\_________ \\ \\
§6       / //     / / / |_|/ / / // //         §c/ / / | |/ / // _________/ / \\________/ / /
§6  ____/ //___  / / /      / / // //_______  §c/ / /  | | / // /|________|/ _________/ / /
§6 /__________/|/_/ /      /_/ //__________/|§c/_/ /   |_ / //_/ /          /__________/ /
§6 |__________|/|_|/       |_|/ |__________|/§c|_|/    |__|/ |_|/           |__________|/
§f
§e      >>>§a   Copyright © IMC.RE 2024
§e      >>>§a   IMCNPS by CymoLink Dev Team
§e      >>>§a   Version: §e%version% §7| §aBuild §e%build_version%
§f
§f           §e○§c-=============[ §f使用前注意§c ]=============-§e○
§f
§f        1. 务必将§eToken§f填写在§e启动参数§f或§enpc\\token.txt§f上
§f        2. 请严格按照联机大厅的§e使用教程§f对IMCNps进行配置
§f        3. IMCNps§c不兼容§f服务器面板环境，请使用§e独立系统机器§f(如VPS)运行
§f        4. 请将§e本体§f与§enpc\\npc.exe§f列入杀毒软件白名单，否则无法正常联机！
§f
"""
not_load_npc_config="§e> §cNpc 配置获取失败，重新连接……"
check_disconnect_reconnect="§e> §c连接已断开，正在重连……"
room_id_tip="""


§e○§c-==========[§f 房间已创建 §c]==========-§e○

§e> §f房间 ID:§b %room_id%
§e> §f让好友在联机大厅输入§b /jr %room_id% §f加入你的房间。

§e○§c-==========[§f 房间已创建 §c]==========-§e○

"""
not_found_token="§e> §cToken未找到！输入 §b/nps <Token>§c 设置你的Token!"
update_check_need_update="""

<yellow>○</yellow><green>-==========[</green><yellow> 版本更新 </yellow><green>]==========-</green><yellow>○</yellow>

<yellow>> </yellow><green>IMCNps 有新版本了!</green>
<yellow>> </yellow><white>下载链接: </white><aqua><underlined><click:open_url:%url%>%url%</click></underlined></aqua>
<yellow>> </yellow><white>请及时更新你的IMCNps，以防无法联机！</white>

<yellow>○</yellow><green>-==========[</green><yellow> 版本更新 </yellow><green>]==========-</green><yellow>○</yellow>

"""
fabric_before_start="""
"""
fabric_room_id_tip="""

§e○§c-==========[§f 房间已创建 §c]==========-§e○

§e> §f房间 ID:§b %room_id%
§e> §f让好友在联机大厅输入§b /jr %room_id% §f加入你的房间。

§e○§c-==========[§f 房间已创建 §c]==========-§e○

"""
fabric_no_token_tip="""

§e> §f没有Token？请登入联机大厅获取
§e> §a多人游戏 §f→§a 添加服务器 §f→§a 填写服务器地址
§e> §f如果你是§a正版§f玩家，请连接§bcymolink.com
§e> §f如果你是§c非正版§f玩家，请连接§boff.cymolink.com"""

fabric_get_token="""
§e> §a已自动获取Token. 你现在可以去单人游戏开启§e对局域网开放§a了！"""
fabric_already_start="§e> §cIMCNps正在运行！如果你要修改Token，请登入联机大厅获取Token，并重启你的Minecraft客户端。"


screen_title="我的房间"
screen_room_name="房间名称"
screen_room_description="房间描述"
screen_room_node="节点"

screen_no_token="你没有Token！"
screen_join_lobby="加入Cymolink 大厅获取Token"

